# Generated by Django 4.2.29 on 2026-04-11 18:00

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_id_card_photo_customuser_id_card_recto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_card_recto',
            field=models.ImageField(blank=True, null=True, upload_to='id_cards/', validators=[users.validators.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id_card_verso',
            field=models.ImageField(blank=True, null=True, upload_to='id_cards/', validators=[users.validators.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', validators=[users.validators.validate_file_type]),
        ),
    ]
