# Generated by Django 4.2.29 on 2026-05-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profileupdaterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='messages_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
