# Generated by Django 4.2.29 on 2026-04-17 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medications', '__first__'),
        ('prescriptions', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_registration_number', models.CharField(default='', help_text="Numéro d'ordre", max_length=100, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pharm_address', models.TextField()),
                ('pharm_city', models.CharField(max_length=100)),
                ('pharm_phone', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_open_24h', models.BooleanField(default=False)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('pharmacy_license', models.FileField(null=True, upload_to='pharmacy_licenses/', validators=[users.validators.validate_file_type])),
                ('pharmacist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy', to='pharmacy.pharmacist')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_type', models.CharField(choices=[('prescription', "Préparation d'ordonnance"), ('direct', 'Achat direct')], default='prescription', max_length=20)),
                ('withdrawal_method', models.CharField(choices=[('patient', 'Retrait par le patient'), ('caretaker', 'Retrait par le garde-malade')], default='patient', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('preparing', 'En préparation'), ('ready', 'Prête à récupérer'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('patient_message', models.TextField(blank=True)),
                ('pharmacist_note', models.TextField(blank=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Prix total de la commande', max_digits=10)),
                ('estimated_ready', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caretaker', models.ForeignKey(blank=True, help_text='Garde-malade assigné si applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_orders', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_orders', to=settings.AUTH_USER_MODEL)),
                ('pharmacist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_orders', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_orders', to='prescriptions.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacistQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('graduation_year', models.PositiveIntegerField()),
                ('degree_type', models.CharField(max_length=100)),
                ('scan', models.FileField(upload_to='pharmacist_qualifications/', validators=[users.validators.validate_file_type])),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='pharmacy.pharmacist')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Prix de vente DZD en pharmacie', max_digits=8)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_stocks', to='medications.medication')),
                ('pharmacy', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='pharmacy.pharmacy')),
            ],
            options={
                'unique_together': {('pharmacy', 'medication')},
            },
        ),
    ]
