# Generated by Django 4.2.29 on 2026-04-18 11:35

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy',
            old_name='license_number',
            new_name='agreement_number',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='pharmacy_license',
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='cnas_coverage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='agreement_scan',
            field=models.FileField(null=True, upload_to='agreement_scans/', validators=[users.validators.validate_file_type]),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='registre_commerce',
            field=models.FileField(null=True, upload_to='registre_commerce/', validators=[users.validators.validate_file_type]),
        ),
    ]
