# Generated by Django 4.2.29 on 2026-05-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_rename_license_number_pharmacy_agreement_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacystock',
            name='min_threshold',
            field=models.PositiveIntegerField(default=10, help_text="Seuil d'alerte stock bas"),
        ),
    ]
