# Generated by Django 4.2.29 on 2026-03-29 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prescriptions', '0001_initial'),
        ('pharmacy', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('preparing', 'En préparation'), ('ready', 'Prête à récupérer'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('patient_message', models.TextField(blank=True)),
                ('pharmacist_note', models.TextField(blank=True)),
                ('estimated_ready', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_orders', to=settings.AUTH_USER_MODEL)),
                ('pharmacist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_orders', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_orders', to='prescriptions.prescription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
