# Generated by Django 4.2.29 on 2026-05-21 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_add_min_threshold_to_pharmacystock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmacy',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='pharmacyorder',
            options={'ordering': ['-created_at']},
        ),
    ]
