# Generated by Django 4.2.29 on 2026-05-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_alter_pharmacy_options_alter_pharmacyorder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='maps_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
