# Generated by Django 4.2.29 on 2026-03-29 13:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_initial'),
        ('patients', '0002_initial'),
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consultation_type', models.CharField(choices=[('in_person', 'En cabinet'), ('teleconsultation', 'Téléconsultation'), ('home_visit', 'Visite à domicile')], default='in_person', max_length=30)),
                ('status', models.CharField(choices=[('scheduled', 'Planifiée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='scheduled', max_length=20)),
                ('chief_complaint', models.TextField()),
                ('history', models.TextField(blank=True)),
                ('examination', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('doctor_notes', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('vitals', models.JSONField(blank=True, default=dict)),
                ('consulted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations_as_doctor', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations_as_patient', to='patients.patient')),
            ],
            options={
                'ordering': ['-consulted_at'],
            },
        ),
    ]
