# Generated by Django 4.2.29 on 2026-03-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='vitals',
            field=models.TextField(blank=True),
        ),
    ]
