# Generated by Django 4.2.29 on 2026-04-18 11:35

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('caretaker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caretaker',
            name='professional_license_number',
        ),
        migrations.AddField(
            model_name='caretaker',
            name='criminal_record_scan',
            field=models.FileField(null=True, upload_to='caretaker_records/', validators=[users.validators.validate_file_type]),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='tarif_de_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
