# Generated by Django 4.2.29 on 2026-04-30 14:30

from django.db import migrations, models
import django.db.models.deletion
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('caretaker', '0003_caretakertask'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaretakerDiploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('date_obtained', models.DateField()),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='caretaker_diplomas/', validators=[users.validators.validate_file_type])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caretaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomas', to='caretaker.caretaker')),
            ],
        ),
    ]
