# Generated by Django 4.2.29 on 2026-05-15 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caretaker', '0004_caretakerdiploma'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(blank=True, max_length=300)),
                ('medications', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('care_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medication_schedule', to='caretaker.carerequest')),
            ],
        ),
    ]
