# Generated by Django 4.2.29 on 2026-05-18 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caretaker', '0006_carerequest_dates_nullable_message_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CaretakerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('care_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='caretaker.carerequest')),
                ('caretaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='caretaker.caretaker')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caretaker_reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
