# Generated by Django 4.2.29 on 2026-05-21 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caretaker', '0007_caretaker_rating_caretaker_total_reviews_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caretaker',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='medicationschedule',
            options={'ordering': ['-created_at']},
        ),
    ]
