# Generated by Django 4.2.29 on 2026-05-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caretaker', '0008_alter_caretaker_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='maps_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
