# Generated by Django 5.2.12 on 2026-04-08 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_appointments', models.BooleanField(default=True, help_text='Appointment reminders')),
                ('notif_prescriptions', models.BooleanField(default=True, help_text='New prescription alerts')),
                ('notif_pharmacy', models.BooleanField(default=True, help_text='Pharmacy order updates')),
                ('notif_caretaker', models.BooleanField(default=True, help_text='Care request updates')),
                ('notif_system', models.BooleanField(default=True, help_text='System & security alerts')),
                ('notif_email', models.BooleanField(default=False, help_text='Send notifications by email')),
                ('notif_sms', models.BooleanField(default=False, help_text='Send notifications by SMS')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('ar', 'العربية'), ('en', 'English')], default='fr', max_length=5)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=10)),
                ('profile_visible_to_doctors', models.BooleanField(default=True)),
                ('profile_visible_to_caretakers', models.BooleanField(default=True)),
                ('share_medical_data_with_doctor', models.BooleanField(default=True)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
            },
        ),
    ]
