# Generated by Django 4.2.29 on 2026-04-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreferences',
            name='appointment_reminders',
        ),
        migrations.RemoveField(
            model_name='notificationpreferences',
            name='care_request_updates',
        ),
        migrations.RemoveField(
            model_name='notificationpreferences',
            name='lab_result_alerts',
        ),
        migrations.RemoveField(
            model_name='notificationpreferences',
            name='order_status_updates',
        ),
        migrations.RemoveField(
            model_name='notificationpreferences',
            name='prescription_updates',
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='notify_appointment',
            field=models.BooleanField(default=True, help_text='Appointment notifications'),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='notify_caretaker',
            field=models.BooleanField(default=True, help_text='Caretaker request notifications'),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='notify_pharmacy',
            field=models.BooleanField(default=True, help_text='Pharmacy / order notifications'),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='notify_system',
            field=models.BooleanField(default=True, help_text='System notifications'),
        ),
    ]
