# Generated by Django 4.2.29 on 2026-05-22 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0003_message_file_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='userreport',
            name='action_taken',
            field=models.CharField(choices=[('none', 'Aucune action'), ('warn', 'Avertissement envoyé'), ('suspend', 'Compte suspendu'), ('dismissed', 'Signalement ignoré')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='userreport',
            name='admin_notes',
            field=models.TextField(blank=True, help_text="Notes internes de l'admin ayant traité le signalement"),
        ),
        migrations.AddField(
            model_name='userreport',
            name='category',
            field=models.CharField(choices=[('harassment', 'Harcèlement / propos insultants'), ('spam', 'Spam ou publicité'), ('fraud', 'Tentative de fraude / arnaque'), ('inappropriate', 'Contenu inapproprié'), ('misinformation', 'Désinformation médicale'), ('other', 'Autre')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='userreport',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userreport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['status', '-created_at'], name='messaging_u_status_2ac209_idx'),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['reported_user', 'status'], name='messaging_u_reporte_71b06b_idx'),
        ),
    ]
