# Generated by Django 4.2.29 on 2026-03-29 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('molecule', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('cardio', 'Cardiologie'), ('diabetes', 'Diabétologie'), ('antibiotic', 'Antibiotique'), ('analgesic', 'Analgésique'), ('anti_inflam', 'Anti-inflammatoire'), ('gastro', 'Gastro-entérologie'), ('neuro', 'Neurologie'), ('other', 'Autre')], default='other', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('dosage_forms', models.JSONField(default=list)),
                ('side_effects', models.TextField(blank=True)),
                ('interactions', models.TextField(blank=True)),
                ('contraindications', models.TextField(blank=True)),
                ('price_dzd', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cnas_covered', models.BooleanField(default=False)),
                ('requires_prescription', models.BooleanField(default=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'En attente CNAS')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('valid_until', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='consultations.consultation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_token', to='prescriptions.prescription')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=200)),
                ('molecule', models.CharField(blank=True, max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('1x_day', '1 fois/jour'), ('2x_day', '2 fois/jour'), ('3x_day', '3 fois/jour'), ('every_8h', 'Toutes les 8h'), ('as_needed', 'Au besoin')], max_length=20)),
                ('duration', models.CharField(max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='CNASCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnas_number', models.CharField(max_length=100)),
                ('coverage_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('covered_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('patient_pays', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cnas_coverage', to='prescriptions.prescription')),
            ],
        ),
    ]
