# Generated by Django 4.2.29 on 2026-04-24 22:08

import diagnostic_ai.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_rename_license_number_doctor_order_number_and_more'),
        ('patients', '0003_treatment_medication_alter_treatment_medication_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('symptoms_text', models.TextField()),
                ('symptoms_en', models.TextField()),
                ('lang', models.CharField(default='fr', max_length=5)),
                ('response', models.TextField()),
                ('recommendation', models.TextField()),
                ('diseases', models.JSONField(default=list)),
                ('specialist', models.JSONField(default=dict)),
                ('urgency', models.CharField(default='modéré', max_length=20)),
                ('hit_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cache diagnostic',
                'ordering': ['-hit_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneticRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.IntegerField()),
                ('best_fitness', models.FloatField()),
                ('best_chromosome', models.JSONField()),
                ('population_size', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Run génétique',
                'ordering': ['-best_fitness', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('question_text', models.TextField()),
                ('lang', models.CharField(default='fr', max_length=5)),
                ('response', models.TextField()),
                ('intent', models.CharField(default='question', max_length=20)),
                ('hit_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cache question',
                'ordering': ['-hit_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('ideal_response', models.TextField()),
                ('diseases', models.JSONField(default=list)),
                ('specialist', models.CharField(max_length=100)),
                ('urgency', models.CharField(max_length=20)),
                ('lang', models.CharField(max_length=5)),
                ('quality_score', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Donnée d'entraînement",
                'ordering': ['-quality_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('response', models.TextField()),
                ('lang', models.CharField(choices=[('fr', 'Français'), ('ar', 'Arabe'), ('en', 'English')], default='fr', max_length=5)),
                ('urgency', models.CharField(choices=[('faible', 'Faible'), ('modere', 'Modéré'), ('urgent', 'Urgent')], default='modere', max_length=20)),
                ('specialist', models.CharField(blank=True, max_length=100)),
                ('feedback', models.IntegerField(blank=True, null=True)),
                ('pending_recommendation', models.TextField(blank=True, null=True)),
                ('recommendation_sent', models.BooleanField(default=False)),
                ('from_cache', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_interactions', to='patients.patient')),
                ('recommended_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_recommendations', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Interaction IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=diagnostic_ai.models.upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_type', models.CharField(choices=[('ordonnance', 'Ordonnance'), ('analyse', 'Analyse médicale'), ('radio', 'Radio / IRM / Scanner'), ('medicament', 'Médicament'), ('compte_rendu', 'Compte rendu'), ('general', 'Document général')], default='general', max_length=20)),
                ('file_size', models.IntegerField(default=0)),
                ('user_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('interaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_upload', to='diagnostic_ai.interaction')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_file_uploads', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Fichier médical IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(default='fr', max_length=5)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('history', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Session de conversation IA',
                'ordering': ['-updated_at'],
            },
        ),
    ]
