# Generated by Django 4.2.29 on 2026-04-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('in_progress', 'En cours'), ('cancelled', 'Annulé'), ('refused', 'Refusé'), ('completed', 'Terminé')], default='pending', max_length=20),
        ),
    ]
