# Generated by Django 4.2.29 on 2026-05-23 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_add_revoked_status_to_link_request'),
        ('appointments', '0003_appointment_external_name_appointment_external_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='external_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='patients.externalpatient'),
        ),
    ]
