# Generated by Django 4.2.29 on 2026-04-18 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_rename_license_number_doctor_order_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antecedent',
            options={'ordering': ['-date_diagnosis']},
        ),
        migrations.AlterModelOptions(
            name='medicaldocument',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='treatment',
            options={'ordering': ['-start_date']},
        ),
        migrations.RemoveField(
            model_name='medicaldocument',
            name='files',
        ),
        migrations.RemoveField(
            model_name='medicalprofile',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='medicalprofile',
            name='chronic_diseases',
        ),
        migrations.RemoveField(
            model_name='medicalprofile',
            name='current_medications',
        ),
        migrations.RemoveField(
            model_name='medicalprofile',
            name='emergency_contact',
        ),
        migrations.AddField(
            model_name='antecedent',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('resolved', 'Résolu'), ('chronic', 'Chronique')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='document_type',
            field=models.CharField(choices=[('lab_result', "Résultat d'analyse"), ('imaging', 'Imagerie (Radio/Scanner)'), ('prescription', 'Ordonnance'), ('report', 'Compte-rendu'), ('other', 'Autre')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='is_visible_to_patient',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='treatment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='prescribed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_treatments', to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='frequency',
            field=models.CharField(blank=True, choices=[('1x_day', '1× par jour'), ('2x_day', '2× par jour'), ('3x_day', '3× par jour'), ('weekly', 'Hebdomadaire'), ('as_needed', 'Si besoin')], max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='medical_documents/%Y/%m/', validators=[users.validators.validate_file_type])),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='patients.medicaldocument')),
            ],
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('mild', 'Légère'), ('moderate', 'Modérée'), ('severe', 'Sévère')], default='mild', max_length=10)),
                ('reaction', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patients.medicalprofile')),
            ],
        ),
    ]
