# Generated by Django 4.2.29 on 2026-04-18 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
        ('patients', '0002_alter_antecedent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_treatments', to='medications.medication'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='medication_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
