# Generated by Django 4.2.29 on 2026-04-13 20:17

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labresult',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='lab_results/', validators=[users.validators.validate_file_type]),
        ),
    ]
