# Generated by Django 4.2.29 on 2026-04-15 15:22

from django.db import migrations, models
import django.db.models.deletion
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_labresult_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('files', models.FileField(blank=True, null=True, upload_to='medical_document/', validators=[users.validators.validate_file_type])),
            ],
        ),
        migrations.RemoveField(
            model_name='symptomanalysis',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='photo',
        ),
        migrations.AddField(
            model_name='treatment',
            name='frequency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='LabResult',
        ),
        migrations.DeleteModel(
            name='SymptomAnalysis',
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to='patients.patient'),
        ),
    ]
