# Generated by Django 4.2.29 on 2026-04-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_symptomanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomanalysis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
