# Generated by Django 4.2.29 on 2026-05-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_externalpatient_patientlinkrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlinkrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté'), ('refused', 'Refusé'), ('revoked', 'Résiliée')], default='pending', max_length=20),
        ),
    ]
