# Generated by Django 4.2.29 on 2026-03-28 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(choices=[('general', 'Médecine Générale'), ('cardiology', 'Cardiologie'), ('dermatology', 'Dermatologie'), ('gynecology', 'Gynécologie'), ('pediatrics', 'Pédiatrie'), ('ophthalmology', 'Ophtalmologie'), ('ent', 'O.R.L'), ('orthopedics', 'Orthopédie'), ('neurology', 'Neurologie'), ('psychiatry', 'Psychiatrie'), ('dentistry', 'Dentisterie'), ('urology', 'Urologie'), ('oncology', 'Oncologie')], default='general', max_length=50)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('clinic_name', models.CharField(blank=True, max_length=200)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('languages', models.CharField(blank=True, help_text='Ex: Français, Arabe, Anglais', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_main_location', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='doctors.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_professionel_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diploma', models.FileField(blank=True, null=True, upload_to='diplomas/')),
                ('order_registration_number', models.CharField(blank=True, max_length=100)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_info', to='doctors.doctor')),
            ],
        ),
    ]
