# Generated by Django 4.2.29 on 2026-04-17 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(choices=[('general', 'Médecine Générale'), ('cardiology', 'Cardiologie'), ('dermatology', 'Dermatologie'), ('gynecology', 'Gynécologie'), ('pediatrics', 'Pédiatrie'), ('ophthalmology', 'Ophtalmologie'), ('ent', 'O.R.L'), ('orthopedics', 'Orthopédie'), ('neurology', 'Neurologie'), ('psychiatry', 'Psychiatrie'), ('dentistry', 'Dentisterie'), ('urology', 'Urologie'), ('oncology', 'Oncologie')], max_length=50)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('practice_authorization', models.FileField(null=True, upload_to='doctor_authorizations/', validators=[users.validators.validate_file_type])),
                ('clinic_name', models.CharField(blank=True, max_length=200)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('languages', models.CharField(blank=True, help_text='Ex: Français, Arabe, Anglais', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment_name', models.CharField(max_length=200)),
                ('est_address', models.TextField()),
                ('est_city', models.CharField(max_length=100)),
                ('pro_phone', models.CharField(blank=True, max_length=10)),
                ('is_main_location', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='doctors.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('graduation_year', models.PositiveIntegerField()),
                ('degree_type', models.CharField(max_length=100)),
                ('scan', models.FileField(upload_to='doctor_qualifications/', validators=[users.validators.validate_file_type])),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='doctors.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration', models.IntegerField(choices=[(15, '15 min'), (20, '20 min'), (30, '30 min'), (45, '45 min'), (60, '1h')], default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Planning hebdomadaire',
                'unique_together': {('doctor', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='DayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_off', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Jour de congé',
                'unique_together': {('doctor', 'date')},
            },
        ),
    ]
