# Generated by Django 4.2.29 on 2026-04-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='license_number',
            new_name='order_number',
        ),
        migrations.AddField(
            model_name='doctor',
            name='cnas_coverage',
            field=models.BooleanField(default=False),
        ),
    ]
