# Generated by Django 4.2.29 on 2026-04-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_rename_license_number_doctor_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyschedule',
            name='break_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='break_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
