# Generated by Django 4.2.29 on 2026-05-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_exercice_latitude_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='maps_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
